#!/bin/bash -e
set -o pipefail

unset TEMPDIR

cleanup() {
	if [ -d "$TEMPDIR" ]; then
		rm -rf "$TEMPDIR"
	fi
}

trap cleanup EXIT

if [ $# -eq 0 ]; then
	echo "Usage: grund <grammar-name> <grun-options...>" >&2
	exit 1
fi

ROOT=$(readlink -f "$(dirname "$0")")
JARS="$ROOT/active/*"

TEMPDIR=$(mktemp -d antlr-grun.XXXXXXXX --tmpdir)
GRAMMAR_NAME=$1
CLASS_NAME=${GRAMMAR_NAME%.g4}
CLASS_NAME=${CLASS_NAME##*/}
shift

antlr -no-listener -Xexact-output-dir -o "$TEMPDIR" "$GRAMMAR_NAME"

javac -d "$TEMPDIR" -cp ".:$JARS:$CLASSPATH" "$TEMPDIR"/*.java

java -cp ".:$JARS:$TEMPDIR:$CLASSPATH" org.antlr.v4.gui.TestRig "$CLASS_NAME" "$@"
